name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Use the latest stable version
    - name: Set up Python
      uses: actions/setup-python@v4 # Use the latest stable version
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Train Model
      run: |
        python model/train.py  # Updated directory path to 'model'
    - name: Evaluate Model
      run: |
        python model/evaluate.py  # Updated directory path to 'model'
    - name: Run Unit Tests
      run: |
        python -m unittest discover -s tests  # Ensure 'tests' folder and files are set up correctly

